extends: stylelint-config-standard
plugins:
  - stylelint-order
rules:
  block-opening-brace-space-before:
  no-descending-specificity:
  string-quotes: single
  order/properties-alphabetical-order: true
